### PR TITLE
Support persistent cache dir command line arg.

### PR DESCRIPTION
**Pull request by Kurt-von-Laven**
Use the new argument in test-opt-out-integration.py to put the
persistent cache directory in a temporary directory so that
make check no longer assumes make install has been run.

[endlessm/eos-sdk#3151]

### CODE REVIEW

**Comment by Kurt-von-Laven** [comment]
The first four commits are intended for cherry-picking to eos2.4:

```
Fix uninitialized memory bug.
Make persistent cache dir before it's needed.
Don't proceed without persistent cache.
Fix memory leaks of GErrors.
```

The rest can be cherry-picked or left on master for convenience.

**Comment by ptomato** [comment]
I merged the four essential commits, even though the tests didn't pass for me locally, because I figured that the same thing happened on master and the tests still passed on Jenkins. I should have been more careful — that situation was of course upgraded from a warning to a fatal error in the commits that I merged.

Here's the test log from my machine:
```
=======================================================
   EOS Event Recorder Daemon 0.0.0: ./test-suite.log
=======================================================

# TOTAL: 11
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/test-opt-out-integration
====================================

1439330382.138 GetAll org.freedesktop.login1.Manager
1439330382.139 Inhibit "shutdown" "EndlessOS Event Recorder Daemon" "Flushing events to disk" "delay"

** (process:27314): WARNING **: Failed to read from cache size file. Error: No such file or directory.

** (process:27314): ERROR **: Could not create persistent cache: Pointer to head of circular file must lie in range [0, 0), but was 0..
FEEE
======================================================================
ERROR: test_opt_out_readable (__main__.TestOptOutIntegration)
Make sure the Enabled property exists.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/test-opt-out-integration.py", line 48, in setUp
    (self.login_popen, self.login_obj) = self.spawn_server_template('logind')
  File "/usr/lib/python3/dist-packages/dbusmock/testcase.py", line 251, in spawn_server_template
    dbus_interface=MOCK_IFACE)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.dbus.exceptions.DBusException: ('org.freedesktop.login1.Manager.PropertyExists', 'property PreparingForShutdown already exists')

======================================================================
ERROR: test_set_enabled_authorized (__main__.TestOptOutIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/test-opt-out-integration.py", line 48, in setUp
    (self.login_popen, self.login_obj) = self.spawn_server_template('logind')
  File "/usr/lib/python3/dist-packages/dbusmock/testcase.py", line 251, in spawn_server_template
    dbus_interface=MOCK_IFACE)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.dbus.exceptions.DBusException: ('org.freedesktop.login1.Manager.PropertyExists', 'property PreparingForShutdown already exists')

======================================================================
ERROR: test_set_enabled_unauthorized (__main__.TestOptOutIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/test-opt-out-integration.py", line 48, in setUp
    (self.login_popen, self.login_obj) = self.spawn_server_template('logind')
  File "/usr/lib/python3/dist-packages/dbusmock/testcase.py", line 251, in spawn_server_template
    dbus_interface=MOCK_IFACE)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.dbus.exceptions.DBusException: ('org.freedesktop.login1.Manager.PropertyExists', 'property PreparingForShutdown already exists')

======================================================================
FAIL: test_opt_out_not_writable (__main__.TestOptOutIntegration)
Make sure the Enabled property is not writable.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/test-opt-out-integration.py", line 55, in setUp
    '/com/endlessm/Metrics', system_bus=True)
  File "/usr/lib/python3/dist-packages/dbusmock/testcase.py", line 184, in wait_for_bus_object
    assert timeout > 0, 'timed out waiting for D-BUS object %s: %s' % (path, last_exc)
AssertionError: timed out waiting for D-BUS object /com/endlessm/Metrics: None

----------------------------------------------------------------------
Ran 4 tests in 5.719s

FAILED (failures=1, errors=3)
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/dbusmock/__main__.py", line 76, in <module>
    bus = dbusmock.testcase.DBusTestCase.get_dbus(args.system)
  File "/usr/lib/python3/dist-packages/dbusmock/testcase.py", line 145, in get_dbus
    return dbus.bus.BusConnection(os.environ['DBUS_SYSTEM_BUS_ADDRESS'])
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-ElVKIQAyaX: Connection refused
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/dbusmock/__main__.py", line 76, in <module>
    bus = dbusmock.testcase.DBusTestCase.get_dbus(args.system)
  File "/usr/lib/python3/dist-packages/dbusmock/testcase.py", line 145, in get_dbus
    return dbus.bus.BusConnection(os.environ['DBUS_SYSTEM_BUS_ADDRESS'])
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-ElVKIQAyaX: Connection refused
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/dbusmock/__main__.py", line 76, in <module>
    bus = dbusmock.testcase.DBusTestCase.get_dbus(args.system)
  File "/usr/lib/python3/dist-packages/dbusmock/testcase.py", line 145, in get_dbus
    return dbus.bus.BusConnection(os.environ['DBUS_SYSTEM_BUS_ADDRESS'])
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-ElVKIQAyaX: Connection refused
```

It looks like it doesn't correctly handle the case where there is no cache size file.

**Comment by Kurt-von-Laven** [comment]
I'm not able to repro this locally, but will try a few more things.

**Comment by Kurt-von-Laven** [comment]
Okay, I am able to reproduce this now by passing `--sysconfdir=/usr/etc`, since there is no `/usr/etc/metrics/cache-size.conf` on my machine. I confirmed that reverting https://github.com/endlessm/eos-event-recorder-daemon/commit/edea83a95bc81354b9bf82d799c7f60a2ee2f5cd prevents the test from failing. I don't understand why the cache size file isn't around though since Automake is configured to install it. Do you happen to know, @ptomato?

**Comment by ptomato** [comment]
@Kurt-von-Laven The build script doesn't run `make install`. More generally, `make check` is supposed to be able to pass without having run `make install` first.

**Comment by Kurt-von-Laven** [comment]
Ah, that is good to know.

**Comment by Kurt-von-Laven** [comment]
I added three new commits:

```
Create cache size file at runtime.
Improve readability of long lines.
Remove curly braces from single statement block.
```

Of these, only the first ("Create cache size file at runtime.") is intended to be cherry-picked to eos2.4.

**Comment by ptomato** [comment]
My tests pass locally. I'll merge the first commit right away and if it fixes the build I'll cherry-pick it; I don't have time to review the other commits just now.

However, you should probably change things so that the installed location of the cache size file is never touched at test time.

**Comment by Kurt-von-Laven** [comment]
The cherry-picked commit fixed the build on Jenkins, but the build failed on OBS. This is the relevant excerpt from the i586 build. I believe the ARM build failed upstream with an unrelated ephemeral error. I believe the build is failing on OBS because of https://github.com/endlessm/eos-event-recorder-daemon/commit/edea83a95bc81354b9bf82d799c7f60a2ee2f5cd. I think the problem is that tests/test-opt-out-integration.py instantiates a production event recorder daemon, which is configured to use paths that shouldn't be used from a test.

```
** (process:26116): ERROR **: Could not create persistent cache: Failed to create directory: /var/cache/metrics/. Error: Permission denied.
FEEETraceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/dbusmock/__main__.py", line 76, in <module>
    bus = dbusmock.testcase.DBusTestCase.get_dbus(args.system)
  File "/usr/lib/python3/dist-packages/dbusmock/testcase.py", line 145, in get_dbus
    return dbus.bus.BusConnection(os.environ['DBUS_SYSTEM_BUS_ADDRESS'])
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-rd3UqzcnGe: Connection refused
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/dbusmock/__main__.py", line 76, in <module>
    bus = dbusmock.testcase.DBusTestCase.get_dbus(args.system)
  File "/usr/lib/python3/dist-packages/dbusmock/testcase.py", line 145, in get_dbus
    return dbus.bus.BusConnection(os.environ['DBUS_SYSTEM_BUS_ADDRESS'])
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-rd3UqzcnGe: Connection refused
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/dbusmock/__main__.py", line 76, in <module>
    bus = dbusmock.testcase.DBusTestCase.get_dbus(args.system)
  File "/usr/lib/python3/dist-packages/dbusmock/testcase.py", line 145, in get_dbus
    return dbus.bus.BusConnection(os.environ['DBUS_SYSTEM_BUS_ADDRESS'])
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-rd3UqzcnGe: Connection refused
```

**Comment by Kurt-von-Laven** [comment]
Specifically the issue is that the opt-out integration test launches the event recorder daemon by spawning its executable: https://github.com/endlessm/eos-event-recorder-daemon/blob/master/tests/test-opt-out-integration.py#L51. I don't know how to fix this test short of deleting it completely since daemon/emer-main.c doesn't have PyGObject bindings.

**Comment by ptomato** [comment]
You could add a command-line switch to specify an alternative to the `/var/cache/metrics` directory.

**Pull request merged**
